version: "2"
linters:
  enable:
    # enabled by default
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes.
    - ineffassign # Detects when assignments to existing variables are not used.
    - staticcheck # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary.
    - unused # Checks Go code for unused constants, variables, functions and types.
    # additional
    - misspell # Finds commonly misspelled English words.
    - sloglint # Ensure consistent code style when using log/slog.
    - godox # Tool for detection of FIXME, TODO and other comment keywords.
    - funlen # Tool for detection of long functions.
    - gocognit # Computes and checks the cognitive complexity of functions.
  settings:
    funlen:
      lines: 60
      statements: 40
      ignore-comments: false
    gocognit:
      min-complexity: 20
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
    sloglint:
      no-mixed-args: true
      kv-only: true
      attr-only: false
      no-global: ""
      context: scope
      static-msg: true
      no-raw-keys: false
      key-naming-case: camel
      forbidden-keys:
        - time
        - level
        - msg
        - source
      args-on-sep-lines: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
