apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "feedbackapi.fullname" $ }}
  labels:
    {{- include "feedbackapi.labels" $ | nindent 4 }}
    app: {{ include "feedbackapi.fullname" $ }}
data:
  {{- range $k, $v := $.Values.configMap }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
