apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedbackapi.fullname" $ }}
  labels:
    {{- include "feedbackapi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: feedback-api
    app: {{ include "feedbackapi.fullname" $ }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: 2222
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "feedbackapi.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: feedback-api
---
