name: Deploy to development
on:
  workflow_dispatch:
  push:
    branches: 
      - main

concurrency:
  group: deploy-dev
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint

  get-current-time:
    runs-on: self-hosted
    outputs:
      time: ${{ steps.current-time.outputs.formattedTime }}
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHmmss

  build:
    needs: [lint, get-current-time]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: meedio/actions/docker-build@v2
        with:
          app-name: feedback-api
          version: 'main-${{ needs.get-current-time.outputs.time }}'

  deploy:
    needs: [build, get-current-time]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        uses: meedio/actions/deploy@v2
        with:
          environment: development
          app-name: feedback-api
          version: 'main-${{ needs.get-current-time.outputs.time }}'
          file-path: 'other/feedback-api/2-feedback-api.yaml'
          kubectl-namespace: feedback-api
          kubectl-object: deployment/feedback-api
