name: golangci-lint
on: workflow_call

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22.5
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
