name: Go Tests
on: workflow_call

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # - name: Download dependencies
      #   run: go mod download

      - name: Run tests
        uses: robherley/go-test-action@v0
